### ISSUE TITLE
Addon Breaks with 11.0.0 and 11.0.2 WoW API Updates

### ISSUE THREAD

**Issue by SabinXna** [dev7355608/ClassicHealPrediction#9]
The addon fails to recognize OnLoad and OnEvent mapping in the xml files.

**Comment by dev7355608** [comment]
I released a small update that should hopefully fix compatibility issues with 1.15.4. I didn't test it though.

**Comment by SabinXna** [comment]
![image](https://github.com/user-attachments/assets/23c2dad1-b6a5-4ade-853f-ae99dea00bc3)
 Still getting the above on that update. 

I managed to get it working with a really bad hack. 

For some reason it's breaking on a pet frame being nil. So I threw a quick if check in createTexture... while it isnt a real fix it's working as a band aid for me. 

![image](https://github.com/user-attachments/assets/2948f35d-eb7f-44fb-9a38-f337742e2d9b)

Hopefully that helps.

**Comment by dev7355608** [comment]
Released another update. Hopefully it works now.

**Comment by Salgat** [comment]
I copy pasted your latest master ClassicHealPrediction.lua and xml from 10 minutes ago and it started working again (no more glowing light sabers at the end of the health bar). Thank you so much for still supporting this addon!!

**Comment by SabinXna** [comment]
Looks good! Thanks!
